name: Daily YouTube Live

on:
  schedule:
    - cron: '30 14 * * *'  # यह हर दिन शाम 8:00 बजे (IST) अपने आप चलेगा
  workflow_dispatch:      # इससे आप जब चाहें खुद भी बटन दबाकर लाइव कर सकते हैं

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Live Stream
        run: |
          ffmpeg -re -i "https://drive.google.com/uc?id=1IV56RSf6Hzwkyuiv2aQ7lmO5cDFPfxevाँ" \
          -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
