name: Morning 9AM Test Live

on:
  schedule:
    - cron: '00 03 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Precise Wait for 9:00 AM IST
        run: |
          target_time=$(date -d "03:30" +%s)
          while [ $(date +%s) -lt $target_time ]; do
            sleep 10
          done

      - name: Run Live Stream
        run: |
          ffmpeg -re -i "https://docs.google.com/uc?export=download&id=1MbfHYBdXAufd1j2Jyg-R9hDL-IE2paoX" \
          -c:v libx264 -preset veryfast -b:v 2500k -maxrate 2500k -bufsize 5000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
